# Generated by Django 3.0.2 on 2020-01-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_points_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
