# Generated by Django 3.0.2 on 2020-01-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200106_1920'),
        ('match', '0003_auto_20200107_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
