# Generated by Django 3.0.2 on 2020-01-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20200107_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='match',
        ),
        migrations.RemoveField(
            model_name='points',
            name='points',
        ),
        migrations.RemoveField(
            model_name='points',
            name='team',
        ),
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Points'),
        ),
        migrations.AddField(
            model_name='points',
            name='team1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='points',
            name='team2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
