# Generated by Django 3.0.2 on 2020-01-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20200107_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Points'),
        ),
    ]
